### ISSUE TITLE
qq邮箱注册

### ISSUE THREAD

**Issue by dada0901** [Laravist/help#2]
因qq邮箱无法收到验证的链接，请协助认证一下吧，谢谢

37773312@qq.com

**Comment by jalenjie** [comment]
注册的时候就建议不要用qq邮箱了.. 但是我的gmail也收不到.

**Comment by JellyBool** [comment]
@dada0901 已通过

**Comment by JellyBool** [comment]
@JalenZack 你用户名是？

**Comment by jalenjie** [comment]
@JellyBool    jalen

**Comment by JellyBool** [comment]
@JalenZack 已OK了
